# Generated by Django 3.1.1 on 2020-10-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20201001_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='post_phone',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='post_content',
            field=models.TextField(blank=True),
        ),
    ]
