# Generated by Django 3.1.1 on 2020-10-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20201001_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='post_phone',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
